# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0215e6dbabd0300761f6a0d94235b4a2d4a669b3c47990a171c6216d21b30f9889778d1c6a36cfb084f06af8445c2902f8d74f91c2b1e6c5af68bfad9a2d2317

test:
  secret_key_base: a3b0de769a47b3e0222fbcac007def89eada8b708a2e85e6030f653bb59dd4be8f1112ffc4b864b62b0644afb8336e0851ff639bbd6e1e813ed87e455d2814c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
